version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:secret@db:5432/basketball
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - SQLALCHEMY_ECHO=true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=basketball
    volumes:
      - ./CreateTables.sql:/docker-entrypoint-initdb.d/1_init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  seed:
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=basketball
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_PORT=5432
    command: python seed_db.py
    depends_on:
      db:
        condition: service_healthy
